FROM kaldiasr/kaldi:gpu-2020-02

RUN git clone --recurse-submodules https://github.com/Voice-Privacy-Challenge/Voice-Privacy-Challenge-2020.git
WORKDIR Voice-Privacy-Challenge-2020


RUN apt-get -y update --fix-missing
RUN apt-get -y install cmake
RUN apt-get -y install python3 python3-pip pkg-config libfreetype6 libfreetype6-dev
RUN pip3 install --upgrade pip
RUN pip3 install scipy sklearn numpy pandas configargparse matplotlib
RUN sed -i 's/Miniconda3-latest-Linux-x86_64/Miniconda3-py37_4.8.2-Linux-x86_64/g' install.sh
RUN ./install.sh
RUN apt-get -y install openssh-server

COPY Experiment Experiment

CMD bash
